<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Métodos de solución</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li>
  <a href="Ayuda.html">¿Cómo utilizar estos apuntes?</a>
</li>
<li>
  <a href="GitHub_en_RStudio.html">Git y GitHub en RStudio</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Contenido
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Unidades</li>
    <li>
      <a href="U1.html">Unidad 1</a>
    </li>
    <li>
      <a href="U2.html">Unidad 2</a>
    </li>
    <li>
      <a href="U3.html">Unidad 3</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Métodos de solución</h1>

</div>


<p>Se abordarán tres métodos de solución para problemas de programación lineal. El primero es el método gráfico, el cual es bastante sencillo y fácil de implementar, con la desventaja de que solo funciona para problemas de dos variables; el segundo será el método <strong>Símplex</strong>, el cual tiene algunas variantes y funciona para cualquier problema, aunque resulta ser largo y por ende, proclive a errores; por último, se verá la solución mediante el programa informático <em>R</em>.</p>
<div id="metodo-grafico" class="section level2">
<h2>Método Gráfico</h2>
<p>Para mostrar en qué consiste el método gráfico, veamos una serie de ejercicios de ejemplo:</p>
<div id="solucion-a-problemas-de-maximizacion" class="section level3">
<h3>Solución a problemas de maximización</h3>
<div id="solucion-optima-unica" class="section level4">
<h4>Solución óptima única</h4>
<p>El problema tendrá una solución única cuando un solo punto del área factible es la solución óptima. Ese punto óptimo debe ser un vértice del área factible.</p>
<div id="ejercicio" class="section level5">
<h5>Ejercicio</h5>
<p>Una empresa fabrica bibliotecas y escritorios, con precios de venta por unidad de <span class="math inline">\(\$9,000\)</span> y <span class="math inline">\(\$10,000\)</span>, respectivamente. Para efectuar la producción, la empresa cuenta con una disponibilidad mensual de 700 metros de madera, 800 metros de tubo y 900 pliegos de papel-lija. Se sabe que una biblioteca consume 7 metros de madera, 10 metros de tubo y 6 pliegos de papel-lija; mientras el escritorio necesita 10 metros de madera, 8 metros de tubo y 15 pliegos de papel-lija. ¿Cuántas bibliotecas y cuántos escritorios debe fabricar si desea el ingreso máximo?</p>
</div>
<div id="solucion" class="section level5">
<h5>Solución</h5>
<p>Este problema puede resolverse con el método gráfico, ya que contiene solo dos variables.</p>
<ol style="list-style-type: decimal">
<li>El primer paso es construir el modelo, lo cual ya se abordó en la unidad anterior. El modelo resultante es:</li>
</ol>
<p><span class="math display">\[
max:Z=9,000x+10,000y\\
\ \\
sujeto\ a:\\
7x+10y\leq700\\
10x+8y\leq800\\
6x+15y\leq900
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>El segundo paso es trazar las restricciones como las desigualdades que son. Si el proceso será a mano, entonces debemos encontrar los puntos donde cada restricción se cruza con los ejes <span class="math inline">\(x\)</span> y <span class="math inline">\(y\)</span>. Comencemos con la primera: <span class="math inline">\(7x+10y\leq700\)</span>. La vamos a tratar como una ecuación lineal y no como una desigualdad. Hacemos nula una de las variables y despejamos para la restante, con el propósito de encontrar el punto de cruce de la línea con el eje de la variable que hicimos cero:</li>
</ol>
<p><span class="math display">\[
Para\ x=0:\\
10y=700\\
y=\frac{700}{10}\\
y=70\\
Coordenada\ de \ cruce: (0,70)
\]</span></p>
<p>Esto nos da el punto de cruce de la línea con el eje <span class="math inline">\(x\)</span>: <span class="math inline">\((0,70)\)</span>. Hacemos lo mismo pero con la otra combinación restante, otra variable nula y el despeje de la que queda:</p>
<p><span class="math display">\[
Para\ y=0:\\
7x=700\\
x=\frac{700}{7}\\
x=100\\
Coordenada\ de \ cruce: (100,0)
\]</span> Siguiendo la misma lógica, obtenemos todos los pares de puntos que representen los cruces de las expresiones con los ejes. Se recomienda hacer esto primero para conocer el tamaño del plano cartesiano que deberemos dibujar en el paso siguiente.</p>
<p>Para la segunda restricción tendremos las coordenadas o puntos en <span class="math inline">\((0,100)\)</span> y en <span class="math inline">\((80,0)\)</span>. Para la tercera, los puntos son <span class="math inline">\((0,60)\)</span> y <span class="math inline">\((150,0)\)</span>. Con todos los puntos obtenidos, comparamos sus valores en <span class="math inline">\(x\)</span> y en <span class="math inline">\(y\)</span>, para saber cuál es el mayor. Resulta ser <span class="math inline">\(150\)</span> para <span class="math inline">\(x\)</span> y <span class="math inline">\(100\)</span> para <span class="math inline">\(y\)</span>. Por lo tanto, el plano debe superar un poco <span class="math inline">\(150\)</span> en el eje horizontal y <span class="math inline">\(100\)</span> en el eje vertical, partiendo siempre desde el origen -debido precisamente a que las variables solo pueden ser positivas en el resultado-.</p>
<ol start="3" style="list-style-type: decimal">
<li>Nos remitimos al par de puntos de la primera restricción. Comenzamos a trazarlos en el plano primero: <span class="math inline">\((0,70)\)</span> y <span class="math inline">\((100,0)\)</span>:</li>
</ol>
<p><img src="images/020-metgraf.png" /></p>
<p>Unimos el par de puntos con una línea recta:</p>
<p><img src="images/021-metgraf.png" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Ahora debemos ubicar lo que llamaremos a partir de ahora la <strong>zona factible</strong>, es decir, la parte delimitada por la restricción. Hay que recordar que la restricción es una desigualdad, por lo que no queda restringida solamente puntos sobre la línea. Más bien, la línea solo representa una de las fronteras, puesto que las otras limitaciones las impone el propio modelo: las restricciones de no negatividad. Para tener una idea un poco mejor, la zona factible queda delimitada por la no negatividad de las variables y la línea que representa la restricción. Como puede notarse, la desigualdad es del tipo <span class="math inline">\(\leq\)</span>, así que la zona factible queda del lado de la recta más cercano al origen del plano. Por lo tanto, podemos trazarla así:</li>
</ol>
<p><img src="images/022-metgraf.png" /></p>
<p>Las desigualdades a las que nos referimos las identificamos de la siguiente manera:</p>
<p><img src="images/023-metgraf.png" /></p>
<ol start="5" style="list-style-type: decimal">
<li>Realizamos lo mismo con el segundo par de puntos. Los trazamos:</li>
</ol>
<p><img src="images/024-metgraf.png" /></p>
<p>Y los unimos:</p>
<p><img src="images/025-metgraf.png" /></p>
<p>Aquí podemos notar algo muy importante. La nueva línea recta corta la zona factible y en apariencia crea otro trozo de la misma. Se debe recalcar que la zona factible solo puede ser limitada por los ejes del plano y líneas rectas, por lo que no debe ser atravesada por nada más. En este caso, el área que la nueva línea recta ha cortado se elimina de la propia zona factible. ¿Cuál área de la zona factible se eliminará? Como la nueva recta representa otra restricción del tipo <span class="math inline">\(\leq\)</span>, entonces el área más lejana al origen del plano es la que se elimina de la zona factible, quedando ésta de la siguiente manera:</p>
<p><img src="images/026-metgraf.png" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Trazamos el último par de puntos:</li>
</ol>
<p><img src="images/027-metgraf.png" /></p>
<p>Trazamos la recta resultante:</p>
<p><img src="images/028-metgraf.png" /></p>
<p>Definimos la nueva zona factible:</p>
<p><img src="images/029-metgraf.png" /></p>
<p>Podemos hacer un acercamiento a la zona factible:</p>
<p><img src="images/030-metgraf.png" /></p>
<ol start="7" style="list-style-type: decimal">
<li>Ya que conocemos la forma de la zona factible, debemos ahora encontrar la solución óptima. Si bien, cualquier punto dentro de la zona factible es una solución al problema, la mejor solución es aquel punto que nos da una función objetivo máxima. Por lo general ese punto se encuentra en uno de los vértices de la zona factible. Por lo tanto, debemos graficar dichos puntos:</li>
</ol>
<p><img src="images/031-metgraf.png" /></p>
<ol start="8" style="list-style-type: decimal">
<li>Es momento de involucrar la función objetivo. Tomamos las coordenadas en <span class="math inline">\(x\)</span> y <span class="math inline">\(y\)</span> de cada vértice y las sustituímos en dicha función. La solución óptima será la mayor que encontremos. Probemos con el primer vértice:</li>
</ol>
<p><span class="math display">\[
Z_1=9,000(0)+10,000(60)=0+600,000
\]</span></p>
<p>Segundo vértice:</p>
<p><span class="math display">\[
Z_2=9,000(33.33)+10,000(46.67)=300,000+466,666.67=766,666.67
\]</span></p>
<p>Tercer vértice: <span class="math display">\[
Z_3=9,000(54.55)+10,000(31.82)=490,950+318200=809,150
\]</span></p>
<p>Cuarto vértice:</p>
<p><span class="math display">\[
Z_4=9,000(80)+10,000(0)=720,000
\]</span></p>
<p>El valor más alto resulta ser el del tercer vértice: <span class="math inline">\(\$809,150\)</span>. Este punto es la solución óptima del problema.</p>
<ol start="9" style="list-style-type: decimal">
<li>La solución del problema es entonces como sigue. Ya que <span class="math inline">\(x\)</span> representa a las bibliotecas, entonces deben fabricarse 54.55 de ellas. En cuanto a los escritorios, estos son representados por <span class="math inline">\(y\)</span>, por lo tanto, deben fabricarse 31.82 escritorios. Si esas cantidades se elaboran, se obtiene un ingreso total de <span class="math inline">\(\$809,150.00\)</span>.</li>
</ol>
</div>
</div>
<div id="solucion-optima-multiple" class="section level4">
<h4>Solución óptima múltiple</h4>
<p>Una solución óptima múltiple ocurre cuando hay por lo menos dos vértices cuya sustitución en la función objetivo dan el máximo valor posible. A continuación veamos un ejercicio que lo ejemplifica.</p>
<div id="ejercicio-1" class="section level5">
<h5>Ejercicio</h5>
<p>Usted dispone semanalmente para la producción de puertas y ventanas con 350 metros de lámina y 360 metros de ángulo. Cada puerta aporta <span class="math inline">\(\$70\)</span> a las utilidades, mientras cada ventana aporta <span class="math inline">\(\$50\)</span> por unidad. Cada puerta requiere 7 metros de lámina y 4 metros de ángulo. Cada ventana requiere 5 metros de lámina y 9 de ángulo. ¿Qué cantidad debe fabricar de cada artículo si se indica que máximo podrá vender 40 puertas?</p>
</div>
<div id="solucion-1" class="section level5">
<h5>Solución</h5>
<p>Primero construiremos el modelo, cuyas variables resultan ser <span class="math inline">\(x\)</span> para la cantidad de puertas fabricadas y <span class="math inline">\(y\)</span> para la de las ventanas. La función objetivo se refiere a la maximización de las utilidades y cada restricción se refiere a un recurso específico. En este caso, se agrega una restricción que tiene que ver más con pronósticos de ventas que con lo funcional de un recurso limitado: el hecho de que solo podrá vender hasta un máximo de 40 puertas. El modelo resultante es el siguiente:</p>
<p><span class="math display">\[
max: Z=70x+50y\\
\ \\
sujeto \ a:\\
7x+5y\leq350\\
4x+9y\leq360\\
x\leq40\\
x,y\geq0
\]</span></p>
<p>El proceso para resolver el problema mediante gráficas es el mismo que en el problema anterior, con la salvedad de que se presenta una restricción univariable: <span class="math inline">\(x\leq40\)</span>. Para esta restricción no es necesario encontrar sus puntos de cruce con algún eje. En realidad, se cruza solamente con el eje <span class="math inline">\(x\)</span> precisamente en el punto 40 del mismo. La zona factible que le corresponde se dirige también hacia el origen, quedando así:</p>
<p><img src="images/032-metgraf.png" /></p>
<p>Mientras tanto, las demás restricciones las trazamos de manera similar al ejemplo anterior, quedando nuestro gráfico de la siguiente manera:</p>
<p><img src="images/033-metgraf.png" /></p>
<p>Trazamos los puntos vértice:</p>
<p><img src="images/034-metgraf.png" /></p>
<p>Si sustituimos todos los puntos en la función objetivo tendremos exactamente el mismo resultado tanto en el punto <span class="math inline">\((31.4,26.04)\)</span> como en el punto <span class="math inline">\((40,14)\)</span>. Dicho resultado es de <span class="math inline">\(\$3,500\)</span> en la función objetivo. Asi que no importa cual de estas dos cantidades fabriquemos, obtendremos la mayor ganancia.</p>
</div>
</div>
<div id="solucion-no-acotada" class="section level4">
<h4>Solución no acotada</h4>
<p>Una fábrica de artesanías elabora bolsos y chamarras. La venta de un bolso aporta <span class="math inline">\(\$2,000\)</span> y consume 5 horas de mano de obra; mientras la chamarra aporta <span class="math inline">\(\$3,000\)</span> y consume 9 horas. Se deben consumir al menos 450 horas de mano de obra por mes. ¿Cuántos bolsos y chamarras debe fabricar si sabe que mínimo venderá 20 chamarras y máximo 30 bolsos?</p>
</div>
<div id="sin-solucion" class="section level4">
<h4>Sin solución</h4>
<p>Produce baldosas y tabletas, generando utilidades por <span class="math inline">\(\$5,000\)</span> y <span class="math inline">\(\$4,000\)</span> por metro cuadrado, respectivamente. Cuenta con 200 metros cuadrados de arena y 240 metros cuadrados de cemento por semana. ¿Cuánto debe fabricar si para un metro cuadrado de baldosas requiere 4 metros cuadrados de arena y 3 de cemento; mientras que para las tabletas necesita 5 metros cuadrados de arena y 8 de cemento? Considere que tiene garantizada la venta de al menos 50 metros cuadrados de tableta.</p>
</div>
</div>
<div id="solucion-a-problemas-de-minimizacion" class="section level3">
<h3>Solución a problemas de minimización</h3>
<div id="solucion-unica-optima" class="section level4">
<h4>Solución única óptima</h4>
<p>Una empresa dedicada a criar caballos ha establecido que es necesario suministrar diariamente a cada uno un mínimo de 200mg de vitamina A, un mínimo de 160mg de vitamina B y un mínimo de 150mg de vitamina C. Los animales son alimentados con matas de pasto y mineral, los cuales cuestan <span class="math inline">\(\$300\)</span> por mata y <span class="math inline">\(\$500\)</span> por libra de mineral. ¿Qué cantidad de cada alimento debe suministrarse a cada caballo diariamente? Se sabe que una mata de pasto aporta 4mg de vitamina A, 2mg de vitamina B y 5mg de vitamina C; mientras que la libra de mineral aporta 5mg de vitamina A, 8mg de vitamina B y 3mg de vitamina C.</p>
<div id="solucion-2" class="section level5">
<h5>Solución</h5>
<p>En este caso el modelo es un poco diferente a los anteriores. Por principio de cuentas, se trata de minimizar costos, asi que podemos esperar que muchas restricciones sean del tipo <span class="math inline">\(\leq\)</span>, aunque eso sí, no es regla que deban ser así. Podemos distinguir que tenemos dos variables, las matas de pasto que serán <span class="math inline">\(x\)</span> y el mineral que será <span class="math inline">\(y\)</span>. Pasamos a modelar el caso, quedando de la siguiente manera:</p>
<p><span class="math display">\[
min:Z=300x+500y\\
\ \\
sujeto\ a:\\
Vitamina\ A:\ 4x+5y\geq200\\
Vitamina\ B:\ 2x+8y\geq160\\
Vitamina\ C:\ 5x+3y\geq150\\
x,y\geq0
\]</span></p>
<p>El método gráfico se lleva a cabo bajo la misma lógica explicada en los problemas anteriores, con la excepción de que las restricciones cuya desigualdad sea del tipo <span class="math inline">\(\geq\)</span> implican una zona factible del lado de la recta lejano al origen del plano. Por ejemplo, veamos cómo queda la línea representativa de la primera restricción:</p>
<p><img src="images/035-metgraf.png" /></p>
<p>La zona factible debe quedar del lado opuesto al origen del plano, como si estuviera pues a la derecha de la línea, quedando como en la siguiente imagen:</p>
<p><img src="images/036-metgraf.png" /></p>
<p>Con todo lo anterior en mente, trazamos las desigualdades y los puntos vértice posteriores. El gráfico completo quedaría así:</p>
<p><img src="images/037-metgraf.png" /></p>
<p>La solución se encuentra en el vértice cuyos valores en <span class="math inline">\(x\)</span> y <span class="math inline">\(y\)</span>, al ser sustituidos en la función objetivo, nos den el valor mínimo. Sustituyamos los resultados:</p>
<p><span class="math display">\[
Z_1=300(0) +500(50)=0+25000=25000\\
Z_2=300(11.5385)+500(30.7692)=3461.55+15384.6=18846.15\\
Z_3=300(36.3636)+500(10.9091)=10909.08+5454.55=16363.63\\
Z_4=300(80)+500(0)=24000+0=24000
\]</span></p>
<p>Con base en estos resultados, podemos concluir que la mejor combinación de matas de pasto y mineral es aquella que nos asegura un costo mínimo de <span class="math inline">\(\$16,363.63\)</span>, consistiendo ésta de 36.3636 matas de pasto y 10.9091 unidades de mineral.</p>
</div>
</div>
<div id="solucion-optima-multiple-1" class="section level4">
<h4>Solución óptima múltiple</h4>
<p>Una empresa de combustibles produce gasolina y ACPM a un costo de <span class="math inline">\(\$20.00\)</span> y <span class="math inline">\(\$40.00\)</span> respectivamente. Para producir un galón de gasolina se requieren 4 horas-hombre, 6 horas-máquina y 8 litros de petróleo. Para cada galón de ACPM son necesarias 8 horas-hombre, 5 horas-máquina y 10 litros de petróleo. Deben consumirse al menos 320 horas-hombre y 300 horas-máquina al mes. ¿Qué cantidad debe producirse si se cuenta con 800 litros mensuales de petróleo?</p>
</div>
<div id="solucion-no-acotada-1" class="section level4">
<h4>Solución no acotada</h4>
<p>La industria siderúrgica un tipo de aleación especial compuesta por sílice y aluminio; los cuales compra a <span class="math inline">\(\$30.00\)</span> y <span class="math inline">\(\$50.00\)</span> por kilogramo, respectivamente. La utilización de un kilogramo de sílice requiere el consumo de 5 miligramos de material radioactivo y dos litros de agua; por otro lado, producir un kilogramo de aluminio requiere consumir 4 miligramos de material radioactivo y produce 3 litros de agua. Por políticas de la empresa, deben consumirse al menos 20 miligramos de material radioactivo y se cuenta con 6 litros de agua. ¿Qué cantidad de sílice y aluminio se debe utilizar si se sabe que como máximo deben utilizarse 8 kilogramos de sílice y que el gobierno subsidia con <span class="math inline">\(\$150.00\)</span> la utilización de cada kilogramo de aluminio?</p>
</div>
<div id="problema-sin-solucion" class="section level4">
<h4>Problema sin solución</h4>
<p>Una empresa zapatera ha establecido que venderá como máximo 30 pares y como mínimo 40 pares de tenis. Para la producción de estos artículos se cuenta con una disponibilidad de mensual de 180 metros de cuero se ha establecido que el costo de producción de cada par de zapatos es de <span class="math inline">\(\$500.00\)</span> y de cada par de tenis de <span class="math inline">\(\$400\)</span>.</p>
</div>
<div id="solucion-degenerada" class="section level4">
<h4>Solución degenerada</h4>
<p>Una empresa produce vidrios florentinos y martillados con un costo de <span class="math inline">\(\$200.00\)</span> y <span class="math inline">\(\$400.00\)</span> por unidad, respectivamente. Se cuenta con una disponibilidad semanal de 240 horas-hombre, 420 horas-horno y 480 unidades de materia prima. Establezca qué cantidad de cada tipo se debe fabricar a fin de minimizar el costo de producción si se sabe que para cada vidrio florentino se requieren 8 horas-hombre, 6 horas en el horno y 16 unidades de materia prima; mientras que para el vidrio martillado son necesarias 3 horas-hombre, 7 horas-horno y 6 unidades de materia prima. Se estima que se venderán mínimo 40 vidrios entre los dos tipos.</p>
</div>
</div>
</div>
<div id="metodo-simplex" class="section level2">
<h2>Método simplex</h2>
<p>Para resolver un modelo de programación lineal mediante el método simplex, se deben tomar en cuenta los siguientes pasos:</p>
<ol style="list-style-type: decimal">
<li>Despejamos la función objetivo, de tal manera que no queden variables del lado derecho de la igualdad.</li>
<li>Transformamos todas las restricciones a igualdades de la siguiente manera:</li>
</ol>
<ul>
<li>Restricción <span class="math inline">\(\leq\)</span>: sumamos una variable de holgura.</li>
<li>Restricción <span class="math inline">\(\geq\)</span>: restamos una variable de sobrante y sumamos una variable artificial. Penalizamos la función objetivo restándole la variable artificial y dando a ésta última un coeficiente infinitamente grande, por ejemplo <span class="math inline">\(-MA_1\)</span>, donde <span class="math inline">\(M\)</span> tienda al infinito.</li>
<li>Restricción <span class="math inline">\(=\)</span>: Sumamos una variable artificial y penalizamos la función objetivo.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Llevamos todos los coeficientes al tablero simplex que se muestra a continuación:</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(X_3\)</span></th>
<th align="center">…</th>
<th align="center"><span class="math inline">\(X_n\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">…</th>
<th align="center"><span class="math inline">\(H_n\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(a_{0i}\)</span></td>
<td align="center"><span class="math inline">\(a_{0i+1}\)</span></td>
<td align="center"><span class="math inline">\(a_{0i+2}\)</span></td>
<td align="center">…</td>
<td align="center"><span class="math inline">\(a_{0n}\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">…</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(H_1\)</span></td>
<td align="center">0</td>
<td align="center"><span class="math inline">\(a_{1i}\)</span></td>
<td align="center"><span class="math inline">\(a_{1i+1}\)</span></td>
<td align="center"><span class="math inline">\(a_{1i+2}\)</span></td>
<td align="center">…</td>
<td align="center"><span class="math inline">\(a_{1n}\)</span></td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">…</td>
<td align="center">0</td>
<td align="center">m</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center"><span class="math inline">\(a_{2i}\)</span></td>
<td align="center"><span class="math inline">\(a_{2i+1}\)</span></td>
<td align="center"><span class="math inline">\(a_{2i+2}\)</span></td>
<td align="center">…</td>
<td align="center"><span class="math inline">\(a_{2n}\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">…</td>
<td align="center">0</td>
<td align="center">n</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center"><span class="math inline">\(a_{3i}\)</span></td>
<td align="center"><span class="math inline">\(a_{3i+1}\)</span></td>
<td align="center"><span class="math inline">\(a_{3i+2}\)</span></td>
<td align="center">…</td>
<td align="center"><span class="math inline">\(a_{3n}\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">…</td>
<td align="center">0</td>
<td align="center">o</td>
</tr>
<tr class="odd">
<td align="right">…</td>
<td align="center">…</td>
<td align="center">0</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">…</td>
<td align="center">p</td>
</tr>
<tr class="even">
<td align="right">n</td>
<td align="center"><span class="math inline">\(H_n\)</span></td>
<td align="center">0</td>
<td align="center"><span class="math inline">\(a_{ni}\)</span></td>
<td align="center"><span class="math inline">\(a_{ni+1}\)</span></td>
<td align="center"><span class="math inline">\(a_{ni+2}\)</span></td>
<td align="center">…</td>
<td align="center"><span class="math inline">\(a_{nn}\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">…</td>
<td align="center">1</td>
<td align="center">q</td>
</tr>
</tbody>
</table>
<ul>
<li>En la fila 0 colocamos solo los coeficientes de la función objetivo, incluyendo los de las variables agregadas, tanto de holgura y sobrante como artificiales.</li>
<li>En la columna <em>base</em> se escriben las variables básicas, que de arranque, son las agregadas al modelo.</li>
<li>En la fila 1 se colocan los coeficientes de la primera restricción, respetando el orden y la variable correspondiente.</li>
<li>En la fila 2 se colocan los coeficientes de la segunda restricción, y así sucesivamente con todas las demás.</li>
<li>En la columna <em>CTE</em> se escriben las constantes de cada restricción.</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Evaluamos si la solución actual es la óptima. Lo sabremos si no existe ningún coeficiente negativo en la fila 0 (la de la función objetivo).</li>
<li>En caso de haber coeficientes negativos, debemos comenzar el método. Seleccionamos la variable que entrará a la base (es decir, se volverá solución). Se escoge aquella cuyo coeficiente en la fila 0 es el más negativo. En caso de empate, se resuelve de manera arbitraria. A su columna se le conocerá como <strong>columna pivote</strong>.</li>
<li>Seleccionamos la variable que saldrá de la base (la que dejará de ser parte de la solución). Para ello dividimos el valor de la columna CTE entre el coeficiente de la columna de la variable que entra a base, en la misma fila. Esto se realiza en todas las filas y se selecciona como la variable de salida a aquella cuyo cociente sea el positivo más bajo; esta fila será la <strong>fila pivote</strong>. Cabe reiterar que se excluyen valores nulos y negativos.</li>
<li>Se selecciona el <strong>elemento pivote</strong>. El cual es aquél donde se cruzan la columna de la variable de entrada y la fila de la variable de salida.</li>
<li>El elemento pivote tiene que volverse unitario, dividiendo toda la fila pivote por el coeficiente del mismo elemento.</li>
<li>Todos los elementos de la columna pivote deben volverse nulos, mediante operaciones matriciales (<em>eliminación de Gauss</em>).</li>
<li>Repetimos el paso 4. En caso de no encontrarse la solución óptima, debemos repetir el ciclo desde el paso 5.</li>
</ol>
<div id="problemas-de-maximizacion." class="section level3">
<h3>Problemas de maximización.</h3>
<p>Retomemos el problema de la misma sección correspondiente al método gráfico, aprovechando que ya tenemos formulado el modelo y conocemos su resultado. Cambiemos las <span class="math inline">\(x\)</span> por <span class="math inline">\(x_1\)</span> y las <span class="math inline">\(y\)</span> por <span class="math inline">\(x_2\)</span>:</p>
<p><span class="math display">\[
f.o.:max\ Z=9,000x_1+10,000x_2\\
\\
\ \\
s.a.\\
7x_1+10x_2\leq700\\
10x_1+8x_2\leq800\\
6x_1+15x_2\leq900\\
x_1,x_2\geq0
\]</span></p>
<p>Reformulemos al modo simplex el modelo. Comencemos con las restricciones, las cuales son todas del tipo <span class="math inline">\(\leq\)</span>. Por lo tanto se agregarán variables de holgura:</p>
<p><span class="math display">\[
7x_1+10x_2+H_1=700\\
10x_1+8x_2+H_2=800\\
6x_1+15x_2+H_3=900
\]</span></p>
<p>Ahora nos pasamos a la función objetivo, a la cual hay que agregarle las variables de holgura con coeficientes nulos:</p>
<p><span class="math display">\[
Z=9,000x_1+10,000x_2+0H_1+0H_2+0H_3
\]</span></p>
<p>Y enseguida despejarla: <span class="math display">\[
Z-9,000x_1-10,000x_2+0H_1+0H_2+0H_3=0
\]</span></p>
<p>Nuestro modelo completo y preparado para simplex quedaría así:</p>
<p><span class="math display">\[
Z-9,000x_1-10,000x_2+0H_1+0H_2+0H_3=0\\
7x_1+10x_2+H_1=700\\
10x_1+8x_2+H_2=800\\
6x_1+15x_2+H_3=900
\]</span></p>
<p>Construyamos ahora el tablero simplex únicamente con los coeficientes del modelo:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-9,000</td>
<td align="center">-10,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(H_1\)</span></td>
<td align="center">0</td>
<td align="center">7</td>
<td align="center">10</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">700</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">10</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">800</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center">6</td>
<td align="center">15</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">900</td>
</tr>
</tbody>
</table>
<pre><code>##   Z    X1     X2 H1 H2 H3 CTE
## 1 1 -9000 -10000  0  0  0   0
## 2 0     7     10  1  0  0 700
## 3 0    10      8  0  1  0 800
## 4 0     6     15  0  0  1 900</code></pre>
<p>Pasemos a resolverlo. Lo primero es verificar si la solución actual es la óptima, notando que el tener valores negativos en la función objetivo implica que no es así.</p>
<p>Lo segundo es determinar la _variable de entrada__, es decir, la que entrará a la <em>base</em>. Para ello seleccionamos el coeficiente más negativo de la fila 0: -10,000. Este pertenece a <span class="math inline">\(x_2\)</span>, por lo tanto, su columna se vuelve ahora la <strong>columna pivote</strong>.</p>
<p>Lo tercero es definir cuál variable de base saldrá de la misma. Para ello tomamos el coeficiente de la columna <em>CTE</em> y lo dividimos entre el coeficiente que le corresponde de la columna pivote (<span class="math inline">\(x_2\)</span>), es decir, dividimos 700 entre 10; 800 entre 8 y 900 entre 15:</p>
<pre><code>## [1]   0  70 100  60</code></pre>
<p>Los resultados obtenidos son los anteriores. Se ignoran negativos y nulos, por lo que el menor es 60. Es el valor correspondiente a la fila 3, es decir, <span class="math inline">\(H_3\)</span>, lo cual la convierte en la <strong>fila pivote</strong>. Con esto, la tabla se modifica para dar cabida a la nueva variable básica, quitando la que deja de serlo:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-9,000</td>
<td align="center">-10,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(H_1\)</span></td>
<td align="center">0</td>
<td align="center">7</td>
<td align="center">10</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">700</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">10</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">800</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">6</td>
<td align="center"><strong>15</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">900</td>
</tr>
</tbody>
</table>
<p>Nuestra atención debe centrarse ahora en el punto de cruce de la fila pivote con la columna pivote. Este punto, o elemento pasa a ser llamado <strong>elemento pivote</strong> y sobre este se centra el simplex, al menos en esta etapa.</p>
<p>Debemos volver <em>unitario</em> al elemento pivote. Para ello, tomamos toda la fila 3 y la dividimos entre 15:</p>
<pre><code>##   Z  X1 X2 H1 H2         H3 CTE
## 4 0 0.4  1  0  0 0.06666667  60</code></pre>
<p>Modificando el tablero para quedar de la siguiente manera, ya con la fila 3 actualizada:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-9,000</td>
<td align="center">-10,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(H_1\)</span></td>
<td align="center">0</td>
<td align="center">7</td>
<td align="center">10</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">700</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">10</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">800</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0.4</td>
<td align="center"><strong>1</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.0667</td>
<td align="center">60</td>
</tr>
</tbody>
</table>
<p>Ahora debemos volver nulo todos los valores de la columna pivote, con excepción del elemento que acabamos de volver unitario. Para ello, tomamos la fila pivote y la multiplicamos por el opuesto aditivo del número que queremos eliminar. Comencemos por el elemento de la fila 0: -10,000. Para eliminarlo, multiplicamos la fila 3 por (10,000), para que al sumarse, se eliminen:</p>
<pre class="r"><code>f0</code></pre>
<pre><code>##   Z    X1     X2 H1 H2 H3 CTE
## 1 1 -9000 -10000  0  0  0   0</code></pre>
<pre class="r"><code>10000*f3</code></pre>
<pre><code>##   Z   X1    X2 H1 H2       H3   CTE
## 4 0 4000 10000  0  0 666.6667 6e+05</code></pre>
<pre class="r"><code>f0 &lt;- f0+10000*f3
f0</code></pre>
<pre><code>##   Z    X1 X2 H1 H2       H3   CTE
## 1 1 -5000  0  0  0 666.6667 6e+05</code></pre>
<p>Ahora eliminemos el 10 que se encuentra en la fila 1. Lo conseguimos multiplicando la fila 3 por (-10) y sumándolo a la fila 1:</p>
<pre class="r"><code>f1</code></pre>
<pre><code>##   Z X1 X2 H1 H2 H3 CTE
## 2 0  7 10  1  0  0 700</code></pre>
<pre class="r"><code>-10*f3</code></pre>
<pre><code>##   Z X1  X2 H1 H2         H3  CTE
## 4 0 -4 -10  0  0 -0.6666667 -600</code></pre>
<pre class="r"><code>f1 &lt;- f1+(-10*f3)
f1</code></pre>
<pre><code>##   Z X1 X2 H1 H2         H3 CTE
## 2 0  3  0  1  0 -0.6666667 100</code></pre>
<p>Enseguida vamos por el elemento que queda en la columna pivote sin ser nulo, el de la fila 2, el cual es un <em>8</em>. Para cancelarlo, multiplicaremos la fila 3 por (-8) y la sumaremos a la fila 2:</p>
<pre class="r"><code>f2</code></pre>
<pre><code>##   Z X1 X2 H1 H2 H3 CTE
## 3 0 10  8  0  1  0 800</code></pre>
<pre class="r"><code>-8*f3</code></pre>
<pre><code>##   Z   X1 X2 H1 H2         H3  CTE
## 4 0 -3.2 -8  0  0 -0.5333333 -480</code></pre>
<pre class="r"><code>f2 &lt;- f2+(-8*f3)
f2</code></pre>
<pre><code>##   Z  X1 X2 H1 H2         H3 CTE
## 3 0 6.8  0  0  1 -0.5333333 320</code></pre>
<p>Procedemos a actualizar nuestro tablero simplex:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-5,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">666.6667</td>
<td align="center">600,000</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(H_1\)</span></td>
<td align="center">0</td>
<td align="center">3</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">-0.6667</td>
<td align="center">100</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">6.8</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.5333</td>
<td align="center">320</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0.4</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.0667</td>
<td align="center">60</td>
</tr>
</tbody>
</table>
<p>Verificamos si ya encontramos la solución óptima. La presencia de (-5,000) en la columna <span class="math inline">\(x1\)</span> indica lo contrario. Por lo tanto, hay que repetir el ciclo. Seleccionamos dicha columna como <em>pivote</em> y buscamos ahora la variable de salida o fila pivote:</p>
<pre class="r"><code>f1[7]/f1[2]</code></pre>
<pre><code>##        CTE
## 2 33.33333</code></pre>
<pre class="r"><code>f2[7]/f2[2]</code></pre>
<pre><code>##        CTE
## 3 47.05882</code></pre>
<pre class="r"><code>f3[7]/f3[2]</code></pre>
<pre><code>##   CTE
## 4 150</code></pre>
<p>El cociente de f1 resulta ser el menor. Por lo tanto, la variable de salida es <span class="math inline">\(H_1\)</span>, convirtiendo a la f1 en la fila pivote. El siguiente paso pues, es volver unitario al elemento pivote:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-5,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">666.6667</td>
<td align="center">600,000</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center"><strong>3</strong></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">-0.6667</td>
<td align="center">100</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">6.8</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.5333</td>
<td align="center">320</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0.4</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.0667</td>
<td align="center">60</td>
</tr>
</tbody>
</table>
<pre class="r"><code>f1 &lt;- f1/3
f1</code></pre>
<pre><code>##   Z X1 X2        H1 H2         H3      CTE
## 2 0  1  0 0.3333333  0 -0.2222222 33.33333</code></pre>
<p>Actualizamos el tablero:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">-5,000</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">666.6667</td>
<td align="center">600,000</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center"><strong>1</strong></td>
<td align="center">0</td>
<td align="center">0.3333</td>
<td align="center">0</td>
<td align="center">-0.2222</td>
<td align="center">33.3333</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">6.8</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.5333</td>
<td align="center">320</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0.4</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.0667</td>
<td align="center">60</td>
</tr>
</tbody>
</table>
<p>Comencemos pues. Hay que volver nulos todos los demás elementos de la columna pivote. Comenzamos por la fila 0, sumándole el producto de la fila 1 por (5,000):</p>
<pre class="r"><code>f0</code></pre>
<pre><code>##   Z    X1 X2 H1 H2       H3   CTE
## 1 1 -5000  0  0  0 666.6667 6e+05</code></pre>
<pre class="r"><code>5000*f1</code></pre>
<pre><code>##   Z   X1 X2       H1 H2        H3      CTE
## 2 0 5000  0 1666.667  0 -1111.111 166666.7</code></pre>
<pre class="r"><code>f0 &lt;- f0+5000*f1
f0</code></pre>
<pre><code>##   Z X1 X2       H1 H2        H3      CTE
## 1 1  0  0 1666.667  0 -444.4444 766666.7</code></pre>
<p>Hagamos nulo al elemento de la siguiente fila, la fila 2:</p>
<pre class="r"><code>f2</code></pre>
<pre><code>##   Z  X1 X2 H1 H2         H3 CTE
## 3 0 6.8  0  0  1 -0.5333333 320</code></pre>
<pre class="r"><code>-6.8*f1</code></pre>
<pre><code>##   Z   X1 X2        H1 H2       H3       CTE
## 2 0 -6.8  0 -2.266667  0 1.511111 -226.6667</code></pre>
<pre class="r"><code>f2 &lt;- f2+(-6.8*f1)
f2</code></pre>
<pre><code>##   Z X1 X2        H1 H2        H3      CTE
## 3 0  0  0 -2.266667  1 0.9777778 93.33333</code></pre>
<p>Ahora al de la fila 3:</p>
<pre class="r"><code>f3</code></pre>
<pre><code>##   Z  X1 X2 H1 H2         H3 CTE
## 4 0 0.4  1  0  0 0.06666667  60</code></pre>
<pre class="r"><code>-0.4*f1</code></pre>
<pre><code>##   Z   X1 X2         H1 H2         H3       CTE
## 2 0 -0.4  0 -0.1333333  0 0.08888889 -13.33333</code></pre>
<pre class="r"><code>f3 &lt;- f3+(-0.4*f1)
f3</code></pre>
<pre><code>##   Z X1 X2         H1 H2        H3      CTE
## 4 0  0  1 -0.1333333  0 0.1555556 46.66667</code></pre>
<p>Actualicemos el tablero:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1,666.6667</td>
<td align="center">0</td>
<td align="center">-444.4444</td>
<td align="center">766,666.7</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0.3333</td>
<td align="center">0</td>
<td align="center">-0.2222</td>
<td align="center">33.3333</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">-2.2667</td>
<td align="center">1</td>
<td align="center">0.9778</td>
<td align="center">93.3333</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.1333</td>
<td align="center">0</td>
<td align="center">0.1556</td>
<td align="center">46.6667</td>
</tr>
</tbody>
</table>
<p>De nuevo podemos notar que no hemos terminado el método, ya que aún tenemos un valor negativo en la función objetivo: <span class="math inline">\(H_3\)</span>. Eso implica que debemos tomar su columna como pivote y definir cuál variable saldrá de base:</p>
<pre class="r"><code>f1[7]/f1[6]</code></pre>
<pre><code>##    CTE
## 2 -150</code></pre>
<pre class="r"><code>f2[7]/f2[6]</code></pre>
<pre><code>##        CTE
## 3 95.45455</code></pre>
<pre class="r"><code>f3[7]/f3[6]</code></pre>
<pre><code>##   CTE
## 4 300</code></pre>
<p>Ignorando el cociente negativo, el menor es el de la fila 2. Por lo tanto, actualizamos el tablero con la variable de entrada en la columna <em>Base</em> y resaltando el elemento pivote:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1,666.6667</td>
<td align="center">0</td>
<td align="center">-444.4444</td>
<td align="center">766,666.7</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0.3333</td>
<td align="center">0</td>
<td align="center">-0.2222</td>
<td align="center">33.3333</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">-2.2667</td>
<td align="center">1</td>
<td align="center"><strong>0.9778</strong></td>
<td align="center">93.3333</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.1333</td>
<td align="center">0</td>
<td align="center">0.1556</td>
<td align="center">46.6667</td>
</tr>
</tbody>
</table>
<p>Obtenemos la nueva fila 2, volviendo unitario al pivote:</p>
<pre class="r"><code>f2.p &lt;- f2[6]
f2.p</code></pre>
<pre><code>##          H3
## 3 0.9777778</code></pre>
<pre class="r"><code>f2 &lt;- f2/0.9777778
f2</code></pre>
<pre><code>##   Z X1 X2        H1       H2 H3      CTE
## 3 0  0  0 -2.318182 1.022727  1 95.45454</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1,666.6667</td>
<td align="center">0</td>
<td align="center">-444.4444</td>
<td align="center">766,666.7</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0.3333</td>
<td align="center">0</td>
<td align="center">-0.2222</td>
<td align="center">33.3333</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">-2.3181</td>
<td align="center">1.0227</td>
<td align="center"><strong>1</strong></td>
<td align="center">95.4545</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">-0.1333</td>
<td align="center">0</td>
<td align="center">0.1556</td>
<td align="center">46.6667</td>
</tr>
</tbody>
</table>
<p>Procedemos a eliminar todos los demás elementos de la columna pivote. Comenzamos con la fila 0:</p>
<pre class="r"><code>f0</code></pre>
<pre><code>##   Z X1 X2       H1 H2        H3      CTE
## 1 1  0  0 1666.667  0 -444.4444 766666.7</code></pre>
<pre class="r"><code>444.444444*f2</code></pre>
<pre><code>##   Z X1 X2        H1       H2       H3      CTE
## 3 0  0  0 -1030.303 454.5454 444.4444 42424.24</code></pre>
<pre class="r"><code>f0 &lt;- f0+(444.444444*f2)
f0</code></pre>
<pre><code>##   Z X1 X2       H1       H2            H3      CTE
## 1 1  0  0 636.3637 454.5454 -1.054545e-05 809090.9</code></pre>
<p>Nótese que el valor resultante para <span class="math inline">\(H_3\)</span> es demasiado pequeño: 0.0000105. Por lo que se considera nulo. Seguimos con la fila 1:</p>
<pre class="r"><code>f1</code></pre>
<pre><code>##   Z X1 X2        H1 H2         H3      CTE
## 2 0  1  0 0.3333333  0 -0.2222222 33.33333</code></pre>
<pre class="r"><code>0.2222*f2</code></pre>
<pre><code>##   Z X1 X2      H1      H2     H3   CTE
## 3 0  0  0 -0.5151 0.22725 0.2222 21.21</code></pre>
<pre class="r"><code>f1 &lt;- f1+0.2222*f2
f1</code></pre>
<pre><code>##   Z X1 X2         H1      H2            H3      CTE
## 2 0  1  0 -0.1817667 0.22725 -2.222727e-05 54.54333</code></pre>
<p>Continuamos con la fila 3:</p>
<pre class="r"><code>f3</code></pre>
<pre><code>##   Z X1 X2         H1 H2        H3      CTE
## 4 0  0  1 -0.1333333  0 0.1555556 46.66667</code></pre>
<pre class="r"><code>-0.1556*f2</code></pre>
<pre><code>##   Z X1 X2        H1         H2      H3       CTE
## 3 0  0  0 0.3607091 -0.1591364 -0.1556 -14.85273</code></pre>
<pre class="r"><code>f3 &lt;- f3+(-0.1556*f2)
f3</code></pre>
<pre><code>##   Z X1 X2        H1         H2            H3      CTE
## 4 0  0  1 0.2273757 -0.1591364 -4.444091e-05 31.81394</code></pre>
<p>Es momento de actualizar el tablero:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_1\)</span></th>
<th align="center"><span class="math inline">\(H_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">636.3637</td>
<td align="center">454.5454</td>
<td align="center">0</td>
<td align="center">809,090.9</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">-0.1817</td>
<td align="center">0.2272</td>
<td align="center">0</td>
<td align="center">54.5433</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">-2.3181</td>
<td align="center">1.0227</td>
<td align="center">1</td>
<td align="center">95.4545</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0.2273</td>
<td align="center">-0.1591</td>
<td align="center">0</td>
<td align="center">31.8139</td>
</tr>
</tbody>
</table>
<p>Verificamos que ya hemos terminado, notando que ya no hay elementos negativos en la función objetivo o fila 0. Lo anterior implica que ya se encontró la solución óptima, la cual pasa por incluir en sí misma solo las variables que se encuentran en la columna <em>Base</em>, así que a partir de este momento, se consideran inválidas las columnas de <span class="math inline">\(H_1\)</span> y <span class="math inline">\(H_2\)</span>. El tablero queda entonces como se muestra:</p>
<table>
<thead>
<tr class="header">
<th align="right">FILA</th>
<th align="center">BASE</th>
<th align="center">Z</th>
<th align="center"><span class="math inline">\(X_1\)</span></th>
<th align="center"><span class="math inline">\(X_2\)</span></th>
<th align="center"><span class="math inline">\(H_3\)</span></th>
<th align="center">CTE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="center">-</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">809,090.9</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_1\)</span></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">54.5433</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="center"><span class="math inline">\(H_3\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">95.4545</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_2\)</span></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">31.8139</td>
</tr>
</tbody>
</table>
<p>Como es notorio, el tablero queda compuesto prácticamente por ceros y unos, con excepción de la fila CTE que contiene los valores constantes del lado derecho de todas las restricciones. Ya podemos leerlo y saber la respuesta al problema:</p>
<p>La función objetivo, representada por <span class="math inline">\(Z\)</span>, es igual a 809,090.9, siendo esto el ingreso máximo que tendrá la empresa si vende las 54.5433 bibliotecas y los 31.8139 escritorios. Datos estos últimos que pueden leerse en el mismo tablero, buscando el dato en la columna CTE que le corresponde a la Base <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span>, respectivamente. Por otro lado, el valor de 95.4545 en <span class="math inline">\(H_3\)</span> significa que esos son los rollos de lija que no serán utilizados. Recordemos que la tercera restricción (de donde salió la variable de holgura <span class="math inline">\(H_3\)</span>) se refiere precisamente a rollos de papel de lija. Nótese que los resultados varían ligeramente con respecto al método gráfico, lo cual se debe a los redondeos que tuvieron que realizarse para los cálculos en dicho método.</p>
</div>
</div>
<div id="metodo-por-computadora" class="section level2">
<h2>Método por computadora</h2>
<p>Para dar por finalizada la unidad, abordaremos la solución del primer problema de programación lineal que se ha realizado. Hemos visto cómo resolver dicho problema por el método gráfico y por el método simplex. Ahora veremos unos cuanto comandos para resolverlo mendiante el programa estadístico R. En sí, resulta más sencillo que graficar o resolver el simplex como tal, debido a que se utiliza la capacidad de cálculo de la computadora. Sin embargo, sí que es necesario un poco de aprendizaje alterno al del modelado. Partamos del mismo problema y su modelo:</p>
<p><span class="math display">\[
f.o.:max\ Z=9,000x_1+10,000x_2\\
\\
\ \\
s.a.\\
7x_1+10x_2\leq700\\
10x_1+8x_2\leq800\\
6x_1+15x_2\leq900\\
x_1,x_2\geq0
\]</span></p>
<p>Para utilizar <em>R</em> es necesario construir otro tablero similar al método simplex, pero no es obligatorio incluir la columna de la variable <span class="math inline">\(Z\)</span>. Basta con escribir una columna por variable, otra para la dirección de la restricción (el símbolo <span class="math inline">\(\leq\)</span> o <span class="math inline">\(\geq\)</span>, según sea el caso) y una última para el valor constante. Por ejemplo, para este problema se construyó el siguiente tablero:</p>
<pre class="r"><code>tablero &lt;- read.table(&quot;datasets/002-lpSolve.txt&quot;, header = T)
tablero</code></pre>
<pre><code>##     x1    x2 dir cte
## 1 9000 10000   -   0
## 2    7    10  &lt;= 700
## 3   10     8  &lt;= 800
## 4    6    15  &lt;= 900</code></pre>
<p>Nótense varias cosas nuevas con esto que se acaba de leer: primero, que se utilizó la variable <code>tablero</code> para asignarle el tablero completo. Pudimos haber utilizado cualquier nombre. Segundo, que el comando <code>read.table</code> funciona para «leer» el contenido de un archivo, dirección del cual se coloca dentro de comillas en primera instancia, y de paréntesis en segunda. Por último, la frase <code>header = T</code> se refiere a que lo que sea que tenga el archivo en la primera fila, se le indica a <em>R</em> que lo tome como el encabezado de las columnas. Si en dado caso no sabemos exactamente la ruta del archivo o tenemos pereza para buscarla o escribirla, podemos colocar la sentencia <code>file.choose()</code> en lugar de todo lo entrecomillado del comando <code>read.table</code>. Esto hará que aparezca la clásica ventana que nos permita buscar el archivo.</p>
<p>Ahora bien, debemos preparar un poco a <em>R</em> para resolver este tipo de problemas, ya que por defecto no contiene el paquete necesario. Para ello si estamos en <em>RStudio</em> nos dirigimos al menú <em>Tools -&gt; Install packages</em> y en el recuadro <em>Packages</em> debemos escribir <code>lpSolve</code>. Debemos asegurarnos de que en <em>Install from:</em> esté seleccionado <code>CRAN</code> y esté seleccionado <em>Install dependencies</em>. Si nos encontramos en <em>R</em> puro (y duro), deberemos realizar esto a golpe de comando, con la sentencia que se muestra a continuación, pero sin la almohadilla (#):</p>
<pre class="r"><code># install.packages(&quot;lpSolve&quot;, dep = T)</code></pre>
<p>A las preguntas que aparezcan se contesta de manera afirmativa. Si solicita un país de descarga se selecciona México.</p>
<p>La prueba de que el paquete se ha instalado de manera correcta es que puede cargarse en <em>R</em> mediante:</p>
<pre class="r"><code>library(lpSolve)</code></pre>
<p>Si no aparece ningún aviso, lpSolve se ha cargado de manera correcta. Ya podemos resolver el problema de ejemplo. Para ello, asignaremos nuevas variables con trozos del tablero que ya hemos invocado. A continuación se muestran dichas variables con los datos que se les han asignado.</p>
<p>Creamos la variable que representará a la función objetivo, extrayendo solamente la primera fila y las dos columnas que contienen los datos relevantes de dicha fila (esto es en realidad lo que se hizo con los números dentro de los corchetes, siendo el primero el número de fila, una coma que separa y los números de columnas en rango, de 1 a 2). A eso que extrajimos lo guardamos en la variable <code>fo</code> en forma de vector:</p>
<pre class="r"><code>fo &lt;- c(tablero[1,1:2])
fo</code></pre>
<pre><code>## $x1
## [1] 9000
## 
## $x2
## [1] 10000</code></pre>
<p>Enseguida creamos la variable donde estarán los coeficientes de las restricciones, seleccionando ya no como vectores a los elementos que se encuentran en el tablero englobados por las filas 2, 3 y 4; y las columnas 1 y 2.</p>
<pre class="r"><code>restricciones &lt;- tablero[2:4,1:2]
restricciones</code></pre>
<pre><code>##   x1 x2
## 2  7 10
## 3 10  8
## 4  6 15</code></pre>
<p>Creamos la variable que contendrá los signos de las restricciones con las filas 2, 3 y 4 y solo la columna 3:</p>
<pre class="r"><code>direcciones &lt;- tablero[2:4,3]
direcciones</code></pre>
<pre><code>## [1] &lt;= &lt;= &lt;=
## Levels: - &lt;=</code></pre>
<p>Para finalizar, creamos la variable que contendrá los valores constantes de las restricciones, con las mismas filas 2, 3 y 4 y solo la última columna, la 4.</p>
<pre class="r"><code>constantes &lt;- tablero[2:4,4]
constantes</code></pre>
<pre><code>## [1] 700 800 900</code></pre>
<p>Ya podemos resolver el problema, con el comando <code>lp</code>, cargado mediante <code>lpSolve</code>:</p>
<pre class="r"><code>solucion &lt;- lp(&quot;max&quot;, fo, restricciones, direcciones, constantes)
solucion</code></pre>
<pre><code>## Success: the objective function is 809090.9</code></pre>
<pre class="r"><code>solucion$solution</code></pre>
<pre><code>## [1] 54.54545 31.81818</code></pre>
<p>Cuando ejecutamos el comando <code>lp</code> el programa calcula el valor de la variable <code>solucion</code>, la cual toma lo que vale la función objetivo. Por lo tanto, <span class="math inline">\(Z\)</span> es igual a 809,090.9. Por otro lado, cuando ejecutamos <code>solucion$solution</code> estamos solicitando los valores de las variables. Nos los dan en orden, <span class="math inline">\(x_1\)</span> primero y <span class="math inline">\(x_2\)</span> después. Dichos valores coinciden con los resultados del método simplex: 54.54545 y 31.81818, respectivamente.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
